### ISSUE TITLE
Chest contents disappear when a TConstruct Smeltery is in the same chunk

### ISSUE THREAD

**Issue by iComputerfreak** [cpw/ironchest#94]
When a chest from the Iron Chests mod is in the same chunk as a smeltery, the contents of the chest sometimes disappear when looking into it.
The contents only disappear visually. Putting items in the chest still works and taking items out too.

It doesn't seem to be just a rendering bug, because when I put items in the "empty" chest, the get put in the first slot. If the chest is empty and I put items in, they will be put back in my inventory when I close the chest.

I had the bug on IronChests version 1.12.2-7.0.46.831, playing the FTB Continuum Modpack without any changes to configs or mods.

I found the workaround on this link: https://forum.feed-the-beast.com/threads/iron-chest-inventory-disappears.291609/

over this link: https://forum.feed-the-beast.com/threads/iron-chest-reinforced-crate-contents-vanish-and-reappear.283883/

**Comment by alexbegt** [comment]
Please create this issue on https://github.com/progwml6/ironchest/

**Comment by iComputerfreak** [comment]
I just moved it. Thanks.

https://github.com/progwml6/ironchest/issues/158
